from formes import *

print("Tests full_line :")
print(full_line(1,'+'))
print(full_line(6,'a'))
print(full_line(2,'/'))
print(full_line(30,'#'))
input()

print("\nTests empty_line :")
print(empty_line(3,'r','8'))
print(empty_line(1,'e','-'))
print(empty_line(10,'-','+'))
print(empty_line(20,'*',' '))
input()

print("\nTests full_rectangle :")
print(full_rectangle(1,5,'+'))
print(full_rectangle(4,1,'-'))
print(full_rectangle(5,5,'*'))
print(full_rectangle(30,3,'h'))
input()

print("\nTests empty_rectangle :")
print(empty_rectangle(1,5,'+','-'))
print(empty_rectangle(4,1,'-','i'))
print(empty_rectangle(5,5,'*',' '))
print(empty_rectangle(30,7,'X','-'))
input()

print("\nTests full_triangle1 :")
print(full_triangle1(1,'+'))
print(full_triangle1(4,'-'))
print(full_triangle1(5,'*'))
print(full_triangle1(15,'X'))
input()

print("\nTests full_triangle2 :")
print(full_triangle2(1,'+','-'))
print(full_triangle2(4,'-','i'))
print(full_triangle2(5,'*',' '))
print(full_triangle2(15,'X',' '))
input()

print("\nTests full_triangle3 :")
print(full_triangle3(1,'+','-'))
print(full_triangle3(4,'-','i'))
print(full_triangle3(5,'*',' '))
print(full_triangle3(15,'X',' '))
input()


print("\nTests empty_triangle1 :")
print(empty_triangle1(1,'+','.'))
print(empty_triangle1(4,'-','o'))
print(empty_triangle1(5,'*','^'))
print(empty_triangle1(15,'X',' '))
input()

print("\nTests empty_triangle2 :")
print(empty_triangle2(1,'+','-'))
print(empty_triangle2(4,'-','i'))
print(empty_triangle2(5,'*',' '))
print(empty_triangle2(15,'X',' '))
input()

print("\nTests empty_triangle3 :")
print(empty_triangle3(1,'+','-'))
print(empty_triangle3(4,'-','i'))
print(empty_triangle3(5,'*',' '))
print(empty_triangle3(15,'X',' '))
